version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5959:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      MAPTILER_API_KEY: ${MAPTILER_API_KEY}
      HIBER_DDL: ${HIBER_DDL}
    restart: unless-stopped
